version: "3.7"
services:

  #Laravel App
  app:
    build:
      context: ./docker/php/${DOCKER_PHP_VERSION}
      dockerfile: Dockerfile.prod
      args:
        xdebug_enabled: ${DOCKER_PHP_XDEBUG_ENABLED}
    image: ${COMPOSE_PROJECT_NAME}-app
    restart: unless-stopped
    tty: true
    working_dir: /var/www/html
    environment:
        XDEBUG_MODE: '${DOCKER_PHP_XDEBUG_MODE:-off}'
    volumes:
      - ./:/var/www/html
    networks:
      - app_network
    depends_on:
      - mysql
      - redis
      - meilisearch
      - minio

  nginx:
    image: nginx:alpine
    restart: unless-stopped
    tty: true
    ports:
      - '${DOCKER_NGINX_PORT:-80}:80'
    volumes:
      - ./:/var/www/html
      - ./docker/nginx/prod/:/etc/nginx/conf.d/
    networks:
      - app_network
    depends_on:
      - app

networks:
  app_network:
    driver: bridge
