version: "3.7"
services:

  #Laravel App
  cron:
    build:
      context: ./docker/php/${DOCKER_PHP_VERSION}
      dockerfile: Dockerfile.cli
      args:
        xdebug_enabled: ${DOCKER_PHP_XDEBUG_ENABLED}
    image: ${COMPOSE_PROJECT_NAME}-cron
    restart: unless-stopped
    tty: true
    working_dir: /var/www/html
    environment:
        XDEBUG_MODE: '${DOCKER_PHP_XDEBUG_MODE:-off}'
    volumes:
      - ./:/var/www/html
    networks:
      - app_network
    command: "su -c 'while true; date; do php artisan schedule:run; sleep 60; done'"

networks:
  app_network:
    driver: bridge
